"use strict";
(function (HoldingsGroupType) {
    HoldingsGroupType[HoldingsGroupType["Detailed"] = 0] = "Detailed";
    HoldingsGroupType[HoldingsGroupType["Currency"] = 1] = "Currency";
    HoldingsGroupType[HoldingsGroupType["AssetClass"] = 2] = "AssetClass";
    HoldingsGroupType[HoldingsGroupType["Country"] = 3] = "Country";
    HoldingsGroupType[HoldingsGroupType["Industry"] = 4] = "Industry";
})(exports.HoldingsGroupType || (exports.HoldingsGroupType = {}));
var HoldingsGroupType = exports.HoldingsGroupType;
(function (Resolution) {
    Resolution[Resolution["month"] = 0] = "month";
    Resolution[Resolution["startOfYear"] = 1] = "startOfYear";
    Resolution[Resolution["last12Monthes"] = 2] = "last12Monthes";
    Resolution[Resolution["last3Years"] = 3] = "last3Years";
    Resolution[Resolution["byDate"] = 4] = "byDate";
})(exports.Resolution || (exports.Resolution = {}));
var Resolution = exports.Resolution;
(function (Parameter) {
    Parameter[Parameter["AllowWebMessageToAdvisor"] = 0] = "AllowWebMessageToAdvisor";
    Parameter[Parameter["ContactToAdvisorFilePath"] = 1] = "ContactToAdvisorFilePath";
    Parameter[Parameter["DefaultHtml"] = 2] = "DefaultHtml";
    Parameter[Parameter["DirectCommunication"] = 3] = "DirectCommunication";
    Parameter[Parameter["EnforcePasswordsHistory"] = 4] = "EnforcePasswordsHistory";
    Parameter[Parameter["FalseLoginsToWebSite"] = 5] = "FalseLoginsToWebSite";
    Parameter[Parameter["ForgotIDMsg"] = 6] = "ForgotIDMsg";
    Parameter[Parameter["IdleTimeForWebSite"] = 7] = "IdleTimeForWebSite";
    Parameter[Parameter["IncomingTiming"] = 8] = "IncomingTiming";
    Parameter[Parameter["IncomingTimingMinutes"] = 9] = "IncomingTimingMinutes";
    Parameter[Parameter["IncomingWatchFile"] = 10] = "IncomingWatchFile";
    Parameter[Parameter["IncomingWebUsersFilePath"] = 11] = "IncomingWebUsersFilePath";
    Parameter[Parameter["IsActiveWebSite"] = 12] = "IsActiveWebSite";
    Parameter[Parameter["IsDMZServer"] = 13] = "IsDMZServer";
    Parameter[Parameter["LogoAlignment"] = 14] = "LogoAlignment";
    Parameter[Parameter["CompanyDisplayName"] = 15] = "CompanyDisplayName";
    Parameter[Parameter["MediatorCommunication"] = 16] = "MediatorCommunication";
    Parameter[Parameter["OutgoingTiming"] = 17] = "OutgoingTiming";
    Parameter[Parameter["OutgoingTimingMinutes"] = 18] = "OutgoingTimingMinutes";
    Parameter[Parameter["OutgoingWatchFile"] = 19] = "OutgoingWatchFile";
    Parameter[Parameter["OutgoingWebUsersFilePath"] = 20] = "OutgoingWebUsersFilePath";
    Parameter[Parameter["PasswordsHistoryCounter"] = 21] = "PasswordsHistoryCounter";
    Parameter[Parameter["WebsiteDataFromDate"] = 22] = "WebsiteDataFromDate";
    Parameter[Parameter["WebsiteDataToDate"] = 23] = "WebsiteDataToDate";
    Parameter[Parameter["WebsiteDefinitionsPath"] = 24] = "WebsiteDefinitionsPath";
    Parameter[Parameter["WebsiteMainColor"] = 25] = "WebsiteMainColor";
    Parameter[Parameter["WebSiteRegistrationType"] = 26] = "WebSiteRegistrationType";
    Parameter[Parameter["WebSiteSendingType"] = 27] = "WebSiteSendingType";
    Parameter[Parameter["WebSiteUpdatesEmail"] = 28] = "WebSiteUpdatesEmail";
    Parameter[Parameter["CompanyWebsiteLink"] = 29] = "CompanyWebsiteLink";
    Parameter[Parameter["ColorsPlate"] = 30] = "ColorsPlate";
    Parameter[Parameter["DisplayTermsOfUseOnLogin"] = 31] = "DisplayTermsOfUseOnLogin";
    Parameter[Parameter["LinkToHomePageForFunds"] = 32] = "LinkToHomePageForFunds";
    Parameter[Parameter["WebSiteUrl"] = 33] = "WebSiteUrl";
    Parameter[Parameter["ContextualColor"] = 34] = "ContextualColor";
    Parameter[Parameter["SMSProvider"] = 35] = "SMSProvider";
    Parameter[Parameter["SMSUser"] = 36] = "SMSUser";
    Parameter[Parameter["SMSPassword"] = 37] = "SMSPassword";
    Parameter[Parameter["HeaderAndTotalColor"] = 38] = "HeaderAndTotalColor";
})(exports.Parameter || (exports.Parameter = {}));
var Parameter = exports.Parameter;
//# sourceMappingURL=models.js.map